/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkdemo_firstndkdemo_JniTest */

#ifndef _Included_com_example_ndkdemo_firstndkdemo_JniTest
#define _Included_com_example_ndkdemo_firstndkdemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkdemo_firstndkdemo_JniTest
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndkdemo_firstndkdemo_JniTest_getName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
